"""empty message

Revision ID: 4a962d52b87c
Revises: 
Create Date: 2023-04-04 14:58:33.705231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a962d52b87c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.drop_column('ticket_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
