"""empty message

Revision ID: ca3a652d130e
Revises: 4a962d52b87c
Create Date: 2023-04-04 14:59:28.381591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3a652d130e'
down_revision = '4a962d52b87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('ticket_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_description', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
